/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InstallRouteImport } from './routes/install'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MIndexRouteImport } from './routes/m.index'
import { Route as MVerificationsRouteImport } from './routes/m.verifications'
import { Route as MSessionsRouteImport } from './routes/m.sessions'
import { Route as AppVerifyRouteImport } from './routes/app.verify'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppPerformanceRouteImport } from './routes/app.performance'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppCyclesRouteImport } from './routes/app.cycles'
import { Route as DotwellKnownAssetlinksDotjsonRouteImport } from './routes/[.]well-known.assetlinks[.]json'
import { Route as AppReportsIndexRouteImport } from './routes/app.reports.index'
import { Route as AppCyclesIndexRouteImport } from './routes/app.cycles.index'
import { Route as PrintVarianceSheetIdRouteImport } from './routes/print.variance-sheet.$id'
import { Route as PrintOutOfSequenceIdRouteImport } from './routes/print.out-of-sequence.$id'
import { Route as PrintCountSummaryIdRouteImport } from './routes/print.count-summary.$id'
import { Route as PrintCountSheetIdRouteImport } from './routes/print.count-sheet.$id'
import { Route as MVerifyIdRouteImport } from './routes/m.verify.$id'
import { Route as MCountIdRouteImport } from './routes/m.count.$id'
import { Route as AppVerifyIdRouteImport } from './routes/app.verify.$id'
import { Route as AppCyclesNewRouteImport } from './routes/app.cycles.new'
import { Route as AppCyclesIdRouteImport } from './routes/app.cycles.$id'
import { Route as AppAdminUsersRouteImport } from './routes/app.admin.users'
import { Route as AppAdminDiagnosticsRouteImport } from './routes/app.admin.diagnostics'
import { Route as AppCyclesIdIndexRouteImport } from './routes/app.cycles.$id.index'
import { Route as AppReportsIdSummaryRouteImport } from './routes/app.reports.$id.summary'
import { Route as AppCyclesIdFinalizeRouteImport } from './routes/app.cycles.$id.finalize'
import { Route as AppCyclesIdCountRouteImport } from './routes/app.cycles.$id.count'
import { Route as AppCyclesIdActivityRouteImport } from './routes/app.cycles.$id.activity'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallRoute = InstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MIndexRoute = MIndexRouteImport.update({
  id: '/m/',
  path: '/m/',
  getParentRoute: () => rootRouteImport,
} as any)
const MVerificationsRoute = MVerificationsRouteImport.update({
  id: '/m/verifications',
  path: '/m/verifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MSessionsRoute = MSessionsRouteImport.update({
  id: '/m/sessions',
  path: '/m/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVerifyRoute = AppVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppPerformanceRoute = AppPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCyclesRoute = AppCyclesRouteImport.update({
  id: '/cycles',
  path: '/cycles',
  getParentRoute: () => AppRoute,
} as any)
const DotwellKnownAssetlinksDotjsonRoute =
  DotwellKnownAssetlinksDotjsonRouteImport.update({
    id: '/.well-known/assetlinks.json',
    path: '/.well-known/assetlinks.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppReportsIndexRoute = AppReportsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppReportsRoute,
} as any)
const AppCyclesIndexRoute = AppCyclesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCyclesRoute,
} as any)
const PrintVarianceSheetIdRoute = PrintVarianceSheetIdRouteImport.update({
  id: '/print/variance-sheet/$id',
  path: '/print/variance-sheet/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintOutOfSequenceIdRoute = PrintOutOfSequenceIdRouteImport.update({
  id: '/print/out-of-sequence/$id',
  path: '/print/out-of-sequence/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintCountSummaryIdRoute = PrintCountSummaryIdRouteImport.update({
  id: '/print/count-summary/$id',
  path: '/print/count-summary/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintCountSheetIdRoute = PrintCountSheetIdRouteImport.update({
  id: '/print/count-sheet/$id',
  path: '/print/count-sheet/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MVerifyIdRoute = MVerifyIdRouteImport.update({
  id: '/m/verify/$id',
  path: '/m/verify/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MCountIdRoute = MCountIdRouteImport.update({
  id: '/m/count/$id',
  path: '/m/count/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVerifyIdRoute = AppVerifyIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppVerifyRoute,
} as any)
const AppCyclesNewRoute = AppCyclesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppCyclesRoute,
} as any)
const AppCyclesIdRoute = AppCyclesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppCyclesRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminDiagnosticsRoute = AppAdminDiagnosticsRouteImport.update({
  id: '/admin/diagnostics',
  path: '/admin/diagnostics',
  getParentRoute: () => AppRoute,
} as any)
const AppCyclesIdIndexRoute = AppCyclesIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCyclesIdRoute,
} as any)
const AppReportsIdSummaryRoute = AppReportsIdSummaryRouteImport.update({
  id: '/$id/summary',
  path: '/$id/summary',
  getParentRoute: () => AppReportsRoute,
} as any)
const AppCyclesIdFinalizeRoute = AppCyclesIdFinalizeRouteImport.update({
  id: '/finalize',
  path: '/finalize',
  getParentRoute: () => AppCyclesIdRoute,
} as any)
const AppCyclesIdCountRoute = AppCyclesIdCountRouteImport.update({
  id: '/count',
  path: '/count',
  getParentRoute: () => AppCyclesIdRoute,
} as any)
const AppCyclesIdActivityRoute = AppCyclesIdActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppCyclesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/install': typeof InstallRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/.well-known/assetlinks.json': typeof DotwellKnownAssetlinksDotjsonRoute
  '/app/cycles': typeof AppCyclesRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/app/performance': typeof AppPerformanceRoute
  '/app/reports': typeof AppReportsRouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/app/verify': typeof AppVerifyRouteWithChildren
  '/m/sessions': typeof MSessionsRoute
  '/m/verifications': typeof MVerificationsRoute
  '/m/': typeof MIndexRoute
  '/app/admin/diagnostics': typeof AppAdminDiagnosticsRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/cycles/$id': typeof AppCyclesIdRouteWithChildren
  '/app/cycles/new': typeof AppCyclesNewRoute
  '/app/verify/$id': typeof AppVerifyIdRoute
  '/m/count/$id': typeof MCountIdRoute
  '/m/verify/$id': typeof MVerifyIdRoute
  '/print/count-sheet/$id': typeof PrintCountSheetIdRoute
  '/print/count-summary/$id': typeof PrintCountSummaryIdRoute
  '/print/out-of-sequence/$id': typeof PrintOutOfSequenceIdRoute
  '/print/variance-sheet/$id': typeof PrintVarianceSheetIdRoute
  '/app/cycles/': typeof AppCyclesIndexRoute
  '/app/reports/': typeof AppReportsIndexRoute
  '/app/cycles/$id/activity': typeof AppCyclesIdActivityRoute
  '/app/cycles/$id/count': typeof AppCyclesIdCountRoute
  '/app/cycles/$id/finalize': typeof AppCyclesIdFinalizeRoute
  '/app/reports/$id/summary': typeof AppReportsIdSummaryRoute
  '/app/cycles/$id/': typeof AppCyclesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/install': typeof InstallRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/.well-known/assetlinks.json': typeof DotwellKnownAssetlinksDotjsonRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/performance': typeof AppPerformanceRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/verify': typeof AppVerifyRouteWithChildren
  '/m/sessions': typeof MSessionsRoute
  '/m/verifications': typeof MVerificationsRoute
  '/m': typeof MIndexRoute
  '/app/admin/diagnostics': typeof AppAdminDiagnosticsRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/cycles/new': typeof AppCyclesNewRoute
  '/app/verify/$id': typeof AppVerifyIdRoute
  '/m/count/$id': typeof MCountIdRoute
  '/m/verify/$id': typeof MVerifyIdRoute
  '/print/count-sheet/$id': typeof PrintCountSheetIdRoute
  '/print/count-summary/$id': typeof PrintCountSummaryIdRoute
  '/print/out-of-sequence/$id': typeof PrintOutOfSequenceIdRoute
  '/print/variance-sheet/$id': typeof PrintVarianceSheetIdRoute
  '/app/cycles': typeof AppCyclesIndexRoute
  '/app/reports': typeof AppReportsIndexRoute
  '/app/cycles/$id/activity': typeof AppCyclesIdActivityRoute
  '/app/cycles/$id/count': typeof AppCyclesIdCountRoute
  '/app/cycles/$id/finalize': typeof AppCyclesIdFinalizeRoute
  '/app/reports/$id/summary': typeof AppReportsIdSummaryRoute
  '/app/cycles/$id': typeof AppCyclesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/install': typeof InstallRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/.well-known/assetlinks.json': typeof DotwellKnownAssetlinksDotjsonRoute
  '/app/cycles': typeof AppCyclesRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/app/performance': typeof AppPerformanceRoute
  '/app/reports': typeof AppReportsRouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/app/verify': typeof AppVerifyRouteWithChildren
  '/m/sessions': typeof MSessionsRoute
  '/m/verifications': typeof MVerificationsRoute
  '/m/': typeof MIndexRoute
  '/app/admin/diagnostics': typeof AppAdminDiagnosticsRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/cycles/$id': typeof AppCyclesIdRouteWithChildren
  '/app/cycles/new': typeof AppCyclesNewRoute
  '/app/verify/$id': typeof AppVerifyIdRoute
  '/m/count/$id': typeof MCountIdRoute
  '/m/verify/$id': typeof MVerifyIdRoute
  '/print/count-sheet/$id': typeof PrintCountSheetIdRoute
  '/print/count-summary/$id': typeof PrintCountSummaryIdRoute
  '/print/out-of-sequence/$id': typeof PrintOutOfSequenceIdRoute
  '/print/variance-sheet/$id': typeof PrintVarianceSheetIdRoute
  '/app/cycles/': typeof AppCyclesIndexRoute
  '/app/reports/': typeof AppReportsIndexRoute
  '/app/cycles/$id/activity': typeof AppCyclesIdActivityRoute
  '/app/cycles/$id/count': typeof AppCyclesIdCountRoute
  '/app/cycles/$id/finalize': typeof AppCyclesIdFinalizeRoute
  '/app/reports/$id/summary': typeof AppReportsIdSummaryRoute
  '/app/cycles/$id/': typeof AppCyclesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/install'
    | '/login'
    | '/signup'
    | '/.well-known/assetlinks.json'
    | '/app/cycles'
    | '/app/dashboard'
    | '/app/performance'
    | '/app/reports'
    | '/app/settings'
    | '/app/verify'
    | '/m/sessions'
    | '/m/verifications'
    | '/m/'
    | '/app/admin/diagnostics'
    | '/app/admin/users'
    | '/app/cycles/$id'
    | '/app/cycles/new'
    | '/app/verify/$id'
    | '/m/count/$id'
    | '/m/verify/$id'
    | '/print/count-sheet/$id'
    | '/print/count-summary/$id'
    | '/print/out-of-sequence/$id'
    | '/print/variance-sheet/$id'
    | '/app/cycles/'
    | '/app/reports/'
    | '/app/cycles/$id/activity'
    | '/app/cycles/$id/count'
    | '/app/cycles/$id/finalize'
    | '/app/reports/$id/summary'
    | '/app/cycles/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/install'
    | '/login'
    | '/signup'
    | '/.well-known/assetlinks.json'
    | '/app/dashboard'
    | '/app/performance'
    | '/app/settings'
    | '/app/verify'
    | '/m/sessions'
    | '/m/verifications'
    | '/m'
    | '/app/admin/diagnostics'
    | '/app/admin/users'
    | '/app/cycles/new'
    | '/app/verify/$id'
    | '/m/count/$id'
    | '/m/verify/$id'
    | '/print/count-sheet/$id'
    | '/print/count-summary/$id'
    | '/print/out-of-sequence/$id'
    | '/print/variance-sheet/$id'
    | '/app/cycles'
    | '/app/reports'
    | '/app/cycles/$id/activity'
    | '/app/cycles/$id/count'
    | '/app/cycles/$id/finalize'
    | '/app/reports/$id/summary'
    | '/app/cycles/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/install'
    | '/login'
    | '/signup'
    | '/.well-known/assetlinks.json'
    | '/app/cycles'
    | '/app/dashboard'
    | '/app/performance'
    | '/app/reports'
    | '/app/settings'
    | '/app/verify'
    | '/m/sessions'
    | '/m/verifications'
    | '/m/'
    | '/app/admin/diagnostics'
    | '/app/admin/users'
    | '/app/cycles/$id'
    | '/app/cycles/new'
    | '/app/verify/$id'
    | '/m/count/$id'
    | '/m/verify/$id'
    | '/print/count-sheet/$id'
    | '/print/count-summary/$id'
    | '/print/out-of-sequence/$id'
    | '/print/variance-sheet/$id'
    | '/app/cycles/'
    | '/app/reports/'
    | '/app/cycles/$id/activity'
    | '/app/cycles/$id/count'
    | '/app/cycles/$id/finalize'
    | '/app/reports/$id/summary'
    | '/app/cycles/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  InstallRoute: typeof InstallRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  DotwellKnownAssetlinksDotjsonRoute: typeof DotwellKnownAssetlinksDotjsonRoute
  MSessionsRoute: typeof MSessionsRoute
  MVerificationsRoute: typeof MVerificationsRoute
  MIndexRoute: typeof MIndexRoute
  MCountIdRoute: typeof MCountIdRoute
  MVerifyIdRoute: typeof MVerifyIdRoute
  PrintCountSheetIdRoute: typeof PrintCountSheetIdRoute
  PrintCountSummaryIdRoute: typeof PrintCountSummaryIdRoute
  PrintOutOfSequenceIdRoute: typeof PrintOutOfSequenceIdRoute
  PrintVarianceSheetIdRoute: typeof PrintVarianceSheetIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install': {
      id: '/install'
      path: '/install'
      fullPath: '/install'
      preLoaderRoute: typeof InstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/': {
      id: '/m/'
      path: '/m'
      fullPath: '/m/'
      preLoaderRoute: typeof MIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/verifications': {
      id: '/m/verifications'
      path: '/m/verifications'
      fullPath: '/m/verifications'
      preLoaderRoute: typeof MVerificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/sessions': {
      id: '/m/sessions'
      path: '/m/sessions'
      fullPath: '/m/sessions'
      preLoaderRoute: typeof MSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/verify': {
      id: '/app/verify'
      path: '/verify'
      fullPath: '/app/verify'
      preLoaderRoute: typeof AppVerifyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/performance': {
      id: '/app/performance'
      path: '/performance'
      fullPath: '/app/performance'
      preLoaderRoute: typeof AppPerformanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cycles': {
      id: '/app/cycles'
      path: '/cycles'
      fullPath: '/app/cycles'
      preLoaderRoute: typeof AppCyclesRouteImport
      parentRoute: typeof AppRoute
    }
    '/.well-known/assetlinks.json': {
      id: '/.well-known/assetlinks.json'
      path: '/.well-known/assetlinks.json'
      fullPath: '/.well-known/assetlinks.json'
      preLoaderRoute: typeof DotwellKnownAssetlinksDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/reports/': {
      id: '/app/reports/'
      path: '/'
      fullPath: '/app/reports/'
      preLoaderRoute: typeof AppReportsIndexRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/app/cycles/': {
      id: '/app/cycles/'
      path: '/'
      fullPath: '/app/cycles/'
      preLoaderRoute: typeof AppCyclesIndexRouteImport
      parentRoute: typeof AppCyclesRoute
    }
    '/print/variance-sheet/$id': {
      id: '/print/variance-sheet/$id'
      path: '/print/variance-sheet/$id'
      fullPath: '/print/variance-sheet/$id'
      preLoaderRoute: typeof PrintVarianceSheetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/out-of-sequence/$id': {
      id: '/print/out-of-sequence/$id'
      path: '/print/out-of-sequence/$id'
      fullPath: '/print/out-of-sequence/$id'
      preLoaderRoute: typeof PrintOutOfSequenceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/count-summary/$id': {
      id: '/print/count-summary/$id'
      path: '/print/count-summary/$id'
      fullPath: '/print/count-summary/$id'
      preLoaderRoute: typeof PrintCountSummaryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/count-sheet/$id': {
      id: '/print/count-sheet/$id'
      path: '/print/count-sheet/$id'
      fullPath: '/print/count-sheet/$id'
      preLoaderRoute: typeof PrintCountSheetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/verify/$id': {
      id: '/m/verify/$id'
      path: '/m/verify/$id'
      fullPath: '/m/verify/$id'
      preLoaderRoute: typeof MVerifyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/count/$id': {
      id: '/m/count/$id'
      path: '/m/count/$id'
      fullPath: '/m/count/$id'
      preLoaderRoute: typeof MCountIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/verify/$id': {
      id: '/app/verify/$id'
      path: '/$id'
      fullPath: '/app/verify/$id'
      preLoaderRoute: typeof AppVerifyIdRouteImport
      parentRoute: typeof AppVerifyRoute
    }
    '/app/cycles/new': {
      id: '/app/cycles/new'
      path: '/new'
      fullPath: '/app/cycles/new'
      preLoaderRoute: typeof AppCyclesNewRouteImport
      parentRoute: typeof AppCyclesRoute
    }
    '/app/cycles/$id': {
      id: '/app/cycles/$id'
      path: '/$id'
      fullPath: '/app/cycles/$id'
      preLoaderRoute: typeof AppCyclesIdRouteImport
      parentRoute: typeof AppCyclesRoute
    }
    '/app/admin/users': {
      id: '/app/admin/users'
      path: '/admin/users'
      fullPath: '/app/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/diagnostics': {
      id: '/app/admin/diagnostics'
      path: '/admin/diagnostics'
      fullPath: '/app/admin/diagnostics'
      preLoaderRoute: typeof AppAdminDiagnosticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cycles/$id/': {
      id: '/app/cycles/$id/'
      path: '/'
      fullPath: '/app/cycles/$id/'
      preLoaderRoute: typeof AppCyclesIdIndexRouteImport
      parentRoute: typeof AppCyclesIdRoute
    }
    '/app/reports/$id/summary': {
      id: '/app/reports/$id/summary'
      path: '/$id/summary'
      fullPath: '/app/reports/$id/summary'
      preLoaderRoute: typeof AppReportsIdSummaryRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/app/cycles/$id/finalize': {
      id: '/app/cycles/$id/finalize'
      path: '/finalize'
      fullPath: '/app/cycles/$id/finalize'
      preLoaderRoute: typeof AppCyclesIdFinalizeRouteImport
      parentRoute: typeof AppCyclesIdRoute
    }
    '/app/cycles/$id/count': {
      id: '/app/cycles/$id/count'
      path: '/count'
      fullPath: '/app/cycles/$id/count'
      preLoaderRoute: typeof AppCyclesIdCountRouteImport
      parentRoute: typeof AppCyclesIdRoute
    }
    '/app/cycles/$id/activity': {
      id: '/app/cycles/$id/activity'
      path: '/activity'
      fullPath: '/app/cycles/$id/activity'
      preLoaderRoute: typeof AppCyclesIdActivityRouteImport
      parentRoute: typeof AppCyclesIdRoute
    }
  }
}

interface AppCyclesIdRouteChildren {
  AppCyclesIdActivityRoute: typeof AppCyclesIdActivityRoute
  AppCyclesIdCountRoute: typeof AppCyclesIdCountRoute
  AppCyclesIdFinalizeRoute: typeof AppCyclesIdFinalizeRoute
  AppCyclesIdIndexRoute: typeof AppCyclesIdIndexRoute
}

const AppCyclesIdRouteChildren: AppCyclesIdRouteChildren = {
  AppCyclesIdActivityRoute: AppCyclesIdActivityRoute,
  AppCyclesIdCountRoute: AppCyclesIdCountRoute,
  AppCyclesIdFinalizeRoute: AppCyclesIdFinalizeRoute,
  AppCyclesIdIndexRoute: AppCyclesIdIndexRoute,
}

const AppCyclesIdRouteWithChildren = AppCyclesIdRoute._addFileChildren(
  AppCyclesIdRouteChildren,
)

interface AppCyclesRouteChildren {
  AppCyclesIdRoute: typeof AppCyclesIdRouteWithChildren
  AppCyclesNewRoute: typeof AppCyclesNewRoute
  AppCyclesIndexRoute: typeof AppCyclesIndexRoute
}

const AppCyclesRouteChildren: AppCyclesRouteChildren = {
  AppCyclesIdRoute: AppCyclesIdRouteWithChildren,
  AppCyclesNewRoute: AppCyclesNewRoute,
  AppCyclesIndexRoute: AppCyclesIndexRoute,
}

const AppCyclesRouteWithChildren = AppCyclesRoute._addFileChildren(
  AppCyclesRouteChildren,
)

interface AppReportsRouteChildren {
  AppReportsIndexRoute: typeof AppReportsIndexRoute
  AppReportsIdSummaryRoute: typeof AppReportsIdSummaryRoute
}

const AppReportsRouteChildren: AppReportsRouteChildren = {
  AppReportsIndexRoute: AppReportsIndexRoute,
  AppReportsIdSummaryRoute: AppReportsIdSummaryRoute,
}

const AppReportsRouteWithChildren = AppReportsRoute._addFileChildren(
  AppReportsRouteChildren,
)

interface AppVerifyRouteChildren {
  AppVerifyIdRoute: typeof AppVerifyIdRoute
}

const AppVerifyRouteChildren: AppVerifyRouteChildren = {
  AppVerifyIdRoute: AppVerifyIdRoute,
}

const AppVerifyRouteWithChildren = AppVerifyRoute._addFileChildren(
  AppVerifyRouteChildren,
)

interface AppRouteChildren {
  AppCyclesRoute: typeof AppCyclesRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppPerformanceRoute: typeof AppPerformanceRoute
  AppReportsRoute: typeof AppReportsRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppVerifyRoute: typeof AppVerifyRouteWithChildren
  AppAdminDiagnosticsRoute: typeof AppAdminDiagnosticsRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCyclesRoute: AppCyclesRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppPerformanceRoute: AppPerformanceRoute,
  AppReportsRoute: AppReportsRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppVerifyRoute: AppVerifyRouteWithChildren,
  AppAdminDiagnosticsRoute: AppAdminDiagnosticsRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  InstallRoute: InstallRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  DotwellKnownAssetlinksDotjsonRoute: DotwellKnownAssetlinksDotjsonRoute,
  MSessionsRoute: MSessionsRoute,
  MVerificationsRoute: MVerificationsRoute,
  MIndexRoute: MIndexRoute,
  MCountIdRoute: MCountIdRoute,
  MVerifyIdRoute: MVerifyIdRoute,
  PrintCountSheetIdRoute: PrintCountSheetIdRoute,
  PrintCountSummaryIdRoute: PrintCountSummaryIdRoute,
  PrintOutOfSequenceIdRoute: PrintOutOfSequenceIdRoute,
  PrintVarianceSheetIdRoute: PrintVarianceSheetIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
